### ISSUE TITLE
Request an App Icon for enigma2 Receivers

### ISSUE THREAD

**Issue by carp3-noctem** [athombv/homey-vectors-public#52]
Hello,
i tryed it by myself, but i didn't get any Icon displayed, when is build an svg file. So my request is, if it is possible for you to build me an App icon showing the linux tux mascon in black&white or as outlines?

Are there any requirements that need to be accounted, when building own icons? Or any Tips, beside the webpage linked in the dev page?

**Comment by IvoDerksen** [comment]
Hello Markus,

There seems to be a problem with icons not displaying. 
See #51 

So I'm not sure if it's the icon that is faulty.

The best tips are: 
- enclose the icon within the artboard / frame / viewport of the SVG
- Use paths, convert lines with stroke to outlines.
- Keep it simple and recognisable.

- Use a cloud SVG converter if you have a great image, but not have the appropriate software.
- Search for similar looking devices on The Nounproject

You can attach the SVG (zipped) to a comment, and I can check it out if you like!

**Comment by carp3-noctem** [comment]
I was going to use this svg file from Wikipedia:
https://en.m.wikipedia.org/wiki/File:Tux_Mono.svg
But it is not shown.
If you can have a look, it would be nice. If there are issues with the icons itself, then that would also declare everything.

I was able to display the kodi logo fine, but as soon as one path was removed, it doesn't show up anymore...

**Comment by IvoDerksen** [comment]
Are you on Android?
Can you send a screenshot of the icon not displaying?
This seems to be related to the referenced issue.

The Tux mono icon should display a fully filled penguin, which isn't desirable, but it's not faulty.

Learn mode //
You can check by opening the SVG in Inkscape or a vector tool (e.g. Illustrator, Sketch).
The SVG consisted of paths overlapping, thus overlapping. making it display one big blob. The white paths should have been be removed from the other path.
//

I fixed this for you, the real-tux-mono SVG is attached.
If you want to learn, compare both SVGs in a vector tool!

[Real-tux_mono.svg.zip](https://github.com/athombv/homey-vectors-public/files/2884029/Real-tux_mono.svg.zip)

**Comment by carp3-noctem** [comment]
I will have a look tonight. Allways happy to learn. 
I have had the issue on both, iOS and Android. It doesn't have done any difference, both didn't show anything.

Will check tonight and report here if this was working or not.

**Comment by carp3-noctem** [comment]
ok, i had a chance to test it before i need to go to work. So both (android & iOS) are still showing empty logos. Both apps are just updated, so i guess it has nothing to do with the Icon itself.
iOS-Screen:
![img_0011](https://user-images.githubusercontent.com/28244954/53086152-d323f080-3504-11e9-813e-14a5bc5a56ea.jpg)
Android-Screen (recorded in Bluestacks):
![bildschirmfoto 2019-02-20 um 11 42 00](https://user-images.githubusercontent.com/28244954/53086162-d7e8a480-3504-11e9-9077-0e0b2b37c07f.png)

**Comment by IvoDerksen** [comment]
Hi Markus, 
Thanks, well so far my superpowers, this is probably like the referenced issue.

Can you report this at:
https://github.com/athombv/homey-apps-sdk-issues/issues
Also add the screenshots for clarification.

Thanks, and sorry for the inconvience!

**Comment by carp3-noctem** [comment]
I've added it over there. But anyway, i will deeper check out the differences with both SVG Files later today and this also will help! 
Thanks for your Support / nice rework!

**Comment by IvoDerksen** [comment]
I'm closing the issue, if you have any questions you can always comment!
Happy coding!
